services:
  db:
    image: mongo
    container_name: db
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./data:/data/db
    networks:
      - db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: homeLibrary